# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: desafio3
  username: postgres
  password: Kronos92
  host: localhost
  port: 5432

test:
  <<: *default
  database: desafio3_test
  username: postgres
  password: Kronos92
  host: localhost

production:
  <<: *default
  database: desafio3_production
  username: postgres
  password: <%= ENV["desafio3_DATABASE_PASSWORD"] %>
